# -*- coding: utf-8 -*-
"""Qualifier 1, part B: does the prospect already have the feature?

Method: one domain-scoped web search per company, so the result comes from
that company's OWN indexed pages rather than from a guess. Prospect sites
cannot be loaded directly from this environment (the egress proxy answers
403 to CONNECT), so this is the strongest available evidence.

The S7.5 batch-4 caveat still applies and is the reason NONE is written as
"none found", never "none": search indexes a tool's landing page, not its
behaviour. A NONE row means no tool page surfaced, which is strong evidence
but not proof. HAS rows are proof, because the tool page itself came back.

tool_level:
  ADVANCED  - a real configurator or room visualiser, live and public
  BASIC     - filters, a swatch picker, a style quiz or a static palette page
  MANUAL    - a custom offering that runs on humans: email, sample books,
              layout simulations done by staff, paper templates
  NONE      - no design or visualisation tool surfaced on their own domain
"""

# company, tool_level, evidence, so_what
F = [
("A.S. Création Tapeten AG","ADVANCED",
 "Room visualisation at /advice-help/room-visualisation plus a configurator: upload your own image, set the format, pick the material, cut to your wall. Separate app at newwalls.as-creation.com, also mobile",
 "They have placement and personalisation already. What they do NOT have is generation. Sell the Imagine-From-Scratch half: their tool needs the customer to arrive holding an image, MEC's invents one from a sentence"),
("Quemere Designs","ADVANCED",
 "Full mosaic builder on its own subdomain, designyourown.quemeredesigns.com: choose a pattern (Flame, Wave, Chevron, Cube, Prism), set up to 4 colours, adjust colour percentages, preview, download a PDF",
 "CORRECTS MY 14 SEPT CALL. I ranked Quemere the top TCNA row on the premise it had no configurator; it has a good one. It moves to the has-a-configurator A/B cohort. The gap is that the builder only recombines preset geometric patterns, it cannot originate a motif"),
("Bankside Decor Ltd (Ohpopsi)","NONE",
 "Ready-made murals only, at set sizes: one design split across six 50cm strips supplied as a roll. No visualiser or configurator surfaced",
 "In-house British designers, 2,000+ designs, and a customer who cannot see any of it on their own wall before buying"),
("Marburger Tapetenfabrik J.B. Schaefer GmbH & Co. KG","NONE",
 "Wallpaper search over 2,000 designs, EUR 1 samples, interactive digital catalogues. Browsing and sample ordering, no visualiser and no configurator",
 "1845, 290 people, collections by named international designers, and the customer journey still ends at posting a paper sample. Priority 1"),
("Driftwood Design Labs","NONE",
 "No tool surfaced. Their own blog post is titled The Importance of Tile Samples in Your Decision-Making Process",
 "They have published an argument for the exact bottleneck MEC removes. Open on their own words"),
("Dunis Studios","BASIC",
 "A picker: choose a tile body (smooth or textured), choose a size, choose a colour. No room view, no pattern composition",
 "Three dropdowns is not a design step. Each tile is described as a small original abstract painting, which is impossible to choose from a list"),
("ECO CERAMICA","BASIC",
 "Search filters by effect, style and room, plus a stated ability to personalise formats, colours and finishes, handled as a consultation",
 "Filters help you find a SKU. They do not help a client approve a bespoke composition"),
("Esselle Retail Limited","NONE",
 "300+ live wallpapers and bespoke own-label collections for global retailers, arranged through account managers. No tool surfaced",
 "Their bespoke loop is an account manager and an email thread. That is the loop, and it is the one MEC compresses"),
("Jeffrey Court","BASIC",
 "No configurator found on the main site. A separate platform exists at hd.jeffreycourt.com; its function could not be confirmed from search",
 "Needs an eyeball on hd.jeffreycourt.com before copy references their tooling. Do not claim they have none"),
("LE NID","NONE",
 "Sicilian ceramics studio (Paterno, CT). Custom kitchen and bathroom tops on single slabs to 2.5m, advanced processing for designers. No tool surfaced",
 "Sells bespoke to designers with no way to show it. Note the tops are 3D-adjacent: confirm the flat-surface share before pitching"),
("LIVDEN","BASIC",
 "A Style Quiz, tile mood boards, a Visualize It feature, and samples inside the Material Bank mood-board builder. Custom designs are handled by emailing Hello@LIVDEN.com",
 "The strongest kind of prospect: they already believe in visual selling (quiz, mood boards, Visualize It) but the CUSTOM path drops to an email address"),
("Linden Workshops","NONE",
 "Three handmade lines (Bronzework Studio, Foundry Art, Talisman), a Where To Buy page, a featured-designer page. No tool surfaced",
 "Bought and renamed in 2024. A new owner is the easiest person in this vertical to sell a new capability to"),
("Maruman Shokai. Co., Ltd.","MANUAL",
 "Their own process page: Maruman uses LAYOUT SIMULATION to create a prospective finished view of your source picture, then the customer confirms colours against a physical tile sample book and approves the composition",
 "THE BEST HOOK IN THE WHOLE LIST. They have written the manual version of MEC Artworks AI into their own process page: a staff-made simulation, a posted sample book, and a wait for approval. 90 colours to choose between, by hand"),
("Mediterra Tile","NONE",
 "A static Glaze Palette page. Glazes applied by hand in small batches, an organic range of values and hues. 12+ years of custom tile. No tool surfaced",
 "Confirms the 14 Sept read. A custom glaze palette with a 4-8 week lead time and nothing to preview against"),
("TECHNOLAM - BLUFANGO","NONE",
 "Large-format thin porcelain slabs. Service described as planning, design, manufacturing AND laying. No tool surfaced",
 "Downgrade: they lay as well as make (gate 3 pressure) and much of the output is worktops and furniture, which is 3D"),
("The Wallfashion House NV","NONE",
 "Collections and inspiration galleries (bedroom ideas, photo wallpaper trends, how-to-apply). Browse and buy, no visualiser and no configurator",
 "1,000+ new designs a year, 20M rolls, 88 countries, and not one way for a customer to see a design on their own wall. Largest design throughput on the list, zero tooling"),
("YUKARI CERAMICS","NONE",
 "Only two pages indexed at all (home, collections). Tiles designed by hand by Japanese artisans",
 "A very thin web presence. Real artisan credentials, almost no digital surface, so the sell is broader than one feature"),
("41ZERO42","NONE",
 "Project galleries and collection catalogues. No tool surfaced",
 "Design-led Italian ceramic brand, no customer-facing design step"),
("AB (AZULEJOS BENADRESA)","ADVANCED",
 "create3d, their 3D Superb program: build your own 3D settings from their collections, multiple laying options, in two versions, HOME for everyone and PRO restricted to professionals",
 "Already solved, and they even segment it by audience. A/B cohort row: what does their 3D room lack that generation adds?"),
("ABK - MOOOI","NONE",
 "Collection catalogue PDFs only (Out.20, Alterego, Concrea, Eco.Chic, Sensi). No tool surfaced",
 "30 years of Made-in-Italy research and the digital surface is a PDF library"),
("AIXIN TECH.CO., LTD","BASIC",
 "5,000+ mosaic SKUs with customised services, inkjet-printed glass mosaic, wall mural art and mosaic murals. No self-serve tool surfaced",
 "They already sell printed mosaic murals, so the product fit is exact. The custom loop is a sales conversation. Tier 3 geography"),
("ALFALUX","NONE",
 "Product collections by effect, surface and format. No tool surfaced",""),
("ALICE CERAMICA","ADVANCED",
 "A Configura Prodotto product configurator with 3D visualisation across their range",
 "RECLASSIFY AS OUT. The range is WCs, bidets, washbasins, bathtubs and shower trays. Sanitaryware, 3D, an explicit S7.4 exclusion. My category gate let it through because 'ceramica' matched the core-niche test"),
("ALVA Surfaces/Wizard","NONE",
 "Almost nothing indexed (two pages). The site now leads as MATERIAL Hospitality, sourcing materials for hospitality projects",
 "Reinforces the 14 Sept gate-3 flag: the public face is now sourcing and specification, not manufacturing"),
("APARICI","ADVANCED",
 "Aparici 3D, described on their own blog as a 3D tile simulator: visualise and personalise a space before buying",
 "Solved. A/B cohort"),
("APPIANI (Gruppo Bardelli)","ADVANCED",
 "THREE live configurators: MyMix (build custom mosaic colour and finish blends), MyDegrade (define gradient progression and intensity), and MyCustom, which transforms ANY IMAGE OR GRAPHIC INTO A CUSTOM CERAMIC MOSAIC",
 "THE MOST IMPORTANT COMPETITIVE FINDING IN THIS PASS. MyCustom is functionally MEC Artworks AI's image-to-mosaic feature, already public, from an Italian mosaic group. It is proof the market wants this, and proof MEC's differentiator cannot be 'turn a picture into a mosaic' - it has to be generation from a description, which MyCustom still cannot do"),
("ARTO Brick & Tile","BASIC",
 "Custom is real and promoted: hand-painted Deco Collections re-coloured to your style, hand-painted murals, and they accept custom design submissions. But submission is by hand",
 "Custom happens through a person receiving a file. 80 staff, LA, founder family still running it"),
("ATLAS CONCORDE","ADVANCED",
 "A published 3D software suite for designers plus a configurator, at /software-3d",
 "Solved, and enterprise. Deprioritise"),
("AZULEV","ADVANCED",
 "HOME DESIGN 3D: create your own 3D environments using the full Azulev ceramic range, at /azulev3d",
 "Solved. A/B cohort"),
("American Glass Mosaics","MANUAL",
 "Create your own custom blend from their colours and finishes; custom logos, glass mosaic murals and artistic mosaics INDIVIDUALLY CREATED AND HAND ASSEMBLED; in-house Italian glass engineers develop blends; customers collaborate with the team to develop their own",
 "A fully human custom-design service, stated plainly on their own customisation page. Only US large-scale 100% recycled glass tile maker. Strong"),
("American Restoration Tile, Inc.","MANUAL",
 "Their own Design Your Own page asks the customer to use COLOURED PENCILS on blank hexagon and square templates, or to post photographs of patterns for the team to recreate. Pricing is by pattern complexity",
 "Second best hook on the list. A paper-and-coloured-pencil design step, in 2026, at a company whose entire business is custom pattern. And because they price on pattern COMPLEXITY, faster iteration has direct margin consequences"),
("BARRO","NONE",
 "Portuguese tile, very thin index (4 pages). No tool surfaced",""),
]

F += [
("BETSAN GLASS MOSAIC","ADVANCED",
 "design.betsan.com, launched as a first in the industry: choose from 101 glass mosaics and 9 porcelain tiles, add grips, gratings and terrace tiles, view the result in daytime AND night-time light, get an instant quantity calculation, download the design",
 "One of the most complete tools found. The night-time pool view is a detail MEC's engine does not do"),
("BOTTEGA","NONE","Collection pages and catalogue PDFs only",""),
("CENTURY","MANUAL",
 "An engineering team accompanies designers and clients through material selection and project development, following each project from design phase to shipment. Pools and wellness is a named specialism",
 "Pool and spa work is the MEC seed niche. The design service is entirely human"),
("CERAMICA RIBESALBES","NONE","Product series pages only",""),
("CERDOMUS","NONE","An interactive catalogue PDF is the only digital surface",""),
("CEVI CERAMICA VIETRESE (Francesco De Maio)","MANUAL",
 "A dedicated Tailor-made page: entirely customised and made-to-measure projects, either from catalogue collections or as unique handmade pieces. Hand-decorated majolica since 1494, with named designer work including Gio Ponti and a Van Gogh collection",
 "Five centuries old, collaborates with world-famous names, sells made-to-measure, and has no way to show a client the result. Top-tier Italian row"),
("CEVICA","ADVANCED",
 "Three tools: a 3D visualizer, Cevica Lab (two applications that let you DESIGN AND CREATE YOUR OWN PRODUCTS for a project), and Overlapp, which shows instantly how a material looks in your room",
 "The closest Spanish equivalent to what MEC sells. Cevica Lab is a design-your-own-product tool, not just a room preview. Strong A/B cohort row"),
("COTTO D'ESTE","NONE","Catalogue and technical-manual PDFs only",""),
("COVERLAM (Grespania)","NONE","Series pages only",""),
("DA VINCI CERAMICA","MANUAL",
 "Ceramic MURAL projects adaptable to any format and fully customisable, plus a projects-to-measure catalogue. Needs are studied per export market and custom solutions offered",
 "Custom ceramic murals to any format is the exact product MEC's engine outputs. The loop is a rep studying a brief"),
("DANILO RAMAZZOTTI IHF","MANUAL",
 "Dedicated technical staff realise projects working on free forms, formats and sample colours; everything made by hand in-house; explicitly offering to go beyond standard production to a true made-to-measure project",
 "Hand-painted majolica with an open-ended format and colour space and a technical staff doing the visualising. Strong"),
("DURSTONE","ADVANCED","A Simulador 3D (Spark Blueprint) plus the Finzzi platform",""),
("EDIMAX ASTOR","NONE",
 "No tool. Their 3D Shaped Technology is a PRODUCTION process for surface realism, not a customer-facing tool",
 "Worth noting the trap: in Italian tile marketing 3D almost always means a relief SURFACE, not a 3D room tool"),
("ELIOS CERAMICA","NONE","Nothing at all returned for the domain. The site may be dead or unindexed. Verify it resolves before any outreach",""),
("ENERGIEKER","NONE","3D Structures are Flow and Groove surface textures, a product not a tool",""),
("ESTUDIO CERAMICO","NONE","Catalogues, collections and a designs gallery. Small-format tile factory",""),
("FAP CERAMICHE","NONE","3D here means relief wall panels and Decor Box, products not tools",""),
("FONCER","OUT-WRONG-COMPANY",
 "foncer.it is FONDO PENSIONE NEGOZIALE, the supplementary PENSION FUND for the Italian ceramics industry, in Sassuolo. Its personalised simulator calculates pension benefits",
 "Not a prospect and not a tile company. A wrong-company row that survived into the enriched set. Delete"),
("FORNACE SUGARONI VINCENZO","MANUAL",
 "Handmade terracotta since 1685. Customer services include creating MOULDS for custom formats, personalised finishes and effects, and technical collaboration",
 "Custom means cutting a new mould. Real, but the pattern space is narrow and the medium is structural terracotta"),
("GAZZINI","NONE","Collections plus personalised expert advice and consulting sessions",""),
("GOMAN","OUT-WRONG-MEDIUM",
 "Accessible and assisted bathrooms: grab rails, technical taps, wall-hung basins for hospitals, care homes and hotels",
 "Sanitaryware and fittings, an explicit S7.4 exclusion. Reclassify OUT"),
("HARMONY","ADVANCED",
 "A 3D tool at /3d headed Configura un ambiente, Disena tu proyecto. Also runs named-designer collections (MUT, Dsignio, Estudi{H}AC)",
 "A design house WITH a configurator. The clearest single test of the has-a-configurator A/B: they already invest in both design and tooling"),
("Hohenberger Manufaktur für Tapeten","NONE",
 "Shop and product pages only. The word Configure on the site is the cookie banner, not a design tool",
 "Checked deliberately: a cookie Configure button is the most common false positive in this kind of scan"),
("INFINITY™","MANUAL",
 "Consultants evaluate design requirements and possible finishes per project; bespoke kitchen tops, vanities, tables and furniture elements from 160x320 slabs",
 "Downgrade: most output is countertops and furniture, which is 3D, and the buyer is a stonemason or interior designer"),
("INSCA","OUT-WRONG-BUSINESS",
 "Makes tile DISPLAY SYSTEMS for showrooms: magnetic sample walls, extensible display panels, custom trade-fair stands. It also sells I.RIS, a digital screen system letting showroom visitors see materials in a real environment",
 "Not a tile maker, so not a prospect. But it sells showroom visualisation technology to exactly our buyers, which makes it a possible CHANNEL PARTNER. Worth a separate conversation"),
("ITA-I.TILES","NONE","Design, production and distribution of Italian ceramic surfaces. Product pages only",""),
("Images In Tile USA","MANUAL",
 "Any image applied to ceramic, porcelain, stone or glass tile, plus customer-supplied tile work. No self-serve upload or preview surfaced",
 "The product is literally image-to-tile-mural and the ordering path is a quote. Exact fit"),
("Jerusalem Heights","NONE","Preset marble mosaic patterns: basketweave, herringbone, hexagon, Paris stripe, mini brick",""),
("KEOPE","ADVANCED",
 "Match App at /tiles/design-your-room: a laying simulator and tile configurator. Upload a photo of your space and see tile combinations in real time",""),
("KT Exclusive GmbH","BASIC",
 "A Tailor made page, digital murals printed to your wall's dimensions on several materials, a wallpaper quantity calculator, and the Muance B2B portal for ordering standard or custom-sized murals",
 "Custom SIZING is solved; custom DESIGN is not. The portal proves they will buy and run web tooling"),
("LA FABBRICA AVA","NONE","Their Imagine series is wallpaper-effect tile, a product not a tool",""),
("LIFE CERAMICA","ADVANCED",
 "A /3d page exists on their own domain, but the indexed content is the cookie notice, so the tool could not be confirmed. Treat as probable, verify by eye",""),
("MARCA CORONA","NONE","4D and 3D here are textured tile collections, plus a Mix and Match style guide. No tool",""),
("MIRAGE","ADVANCED","30+ collections and an invitation to imagine your bathroom, bedroom or living room and create your space with the configurator",""),
("MONOCIBEC","ADVANCED",
 "Thema lets you observe and design an environment at the same time. Separately, Fincibec Engineering supports designers with special-piece proposals and estimates",
 "Tool plus a human engineering service behind it. Same group as Fincibec"),
("Malibu Ceramic Works","MANUAL",
 "Full-spectrum design services for residential and commercial projects, with designers who MEET WITH YOU and guide you through the design process. Rug tile murals and flower pot murals are named product lines",
 "A face-to-face design meeting is the most expensive version of this bottleneck there is"),
("Marazzi/American Olean","ADVANCED-AI",
 "TWO tools. Stylizer: upload your own photo or pick a room scene, design with floor, wall and mosaic tile, save and share. And STYLIZER AI, headed AI Interior Design Starts Here: upload a photo, choose a style such as Scandinavian, Modern Farmhouse or Bohemian, and AI instantly suggests tile selections styled to that look. Also runs Roomvo",
 "THE CLOSEST COMPETITOR TO MEC ARTWORKS AI FOUND ANYWHERE IN THIS DATASET, and it is Mohawk/Dal-Tile, the largest player in the vertical. AI styling from a photo is live and free. This resets what counts as differentiated: room styling is commoditised, originating a bespoke PATTERN is not"),
("McIntyre Tile, Inc.","MANUAL",
 "The Custom Solutions page: send an existing tile, a paint chip or a material sample, and the technical team evaluates tone, variation and reflection, then adjusts and TESTS GLAZE RECIPES AND FIRING CONDITIONS until it matches. Orders only through customer service or a retailer",
 "A physical trial-and-error loop with kiln firings per iteration. The slowest approval cycle on the list"),
("NADIS DESIGN","NONE",
 "Designer collections (Inma Bermudez, Francesc Rife) and an Fe collection 3D LIBRARY, which is BIM and 3D assets for specifiers, not a customer design tool",""),
("OLYMPIA CERAMICA","OUT-WRONG-MEDIUM",
 "Ceramic bathroom fixtures and furnishings: WCs, basins, modular bathroom furniture. Offers 3D models and consultation to architects",
 "Sanitaryware. Reclassify OUT"),
("ONIX","ADVANCED",
 "A full suite. Mosaic Creator web app: pick HEX, PENTA or SQUARE formats, create random mixes, design your own, set the PERCENTAGE of each tile type, choose grout colour, preview, then export to PDF or image or share by email and social. Plus ONIX 3D Rendering for ultra-realistic real-time visualisation, a pool-water colour simulator, and Pixel Art customisation",
 "The most complete mosaic-configurator suite found, from a glass mosaic maker. Along with Appiani's MyCustom this is the competitive ceiling in mosaic"),
("OPTIMUM SURFACES","NONE",
 "Large slabs with custom solutions via professional services. Much of the output is tabletops and furniture",
 "Downgrade on medium, same as Technolam and Infinity"),
("PANARIA CERAMICA","NONE","Collections and magazine articles. ZERO.3 thin slabs are a product",""),
("PETRA ANTIQUA","MANUAL",
 "Stone mosaics and compositions where, in their own words, every proposal can be personalised to fit YOUR WALL'S DIMENSIONS and your artistic taste",
 "They promise per-wall artistic personalisation and offer no way to see it. On-niche and a clean opening line"),
("POLCART","OUT-WRONG-BUSINESS",
 "Custom-made DISPLAY SYSTEMS for ceramic showrooms: printed panels, honeycomb-light supports, synoptic boards",
 "Same category as INSCA. Not a prospect, possible channel partner"),
("POLIS","OUT-MIDDLEMAN",
 "A retail CHAIN of tile and bathroom stores across Rovigo, Monza, Novara, Bergamo, Treviso, Vicenza, Mestre and Sondrio",
 "Retailer. Gate 3. Reclassify OUT"),
("QUINTESSENZA CERAMICHE","NONE","Collections plus a merchandising and display system for professionals",""),
("REVIGRES","NONE","Nothing returned for the domain on this query. Verify the site resolves",""),
("ROCA TILES","ADVANCED",
 "Roca Tiles 3D: realistic visualisation from any angle, real-time changes, a wide selection of materials, colours and textures, furniture placement, and it is free and open access",""),
("Roca / Lamosa USA","ADVANCED","A Visualizer plus a Design Studio section",""),
("SERENISSIMA","NONE","Collections and modular format guidance",""),
("SETTECENTO VALTRESINARO","NONE",
 "A large cloud catalogue of decors and collections including hand-carved three-dimensional processes. No tool",
 "Decor-heavy manufacturer with a deep catalogue and no way to compose from it"),
("SICER","OUT-WRONG-BUSINESS",
 "A colorificio: ceramic glazes, frits, pigments, colouring oxides and digital inks sold to tile manufacturers",
 "Chemical input supplier, an explicit S7.4 exclusion. Reclassify OUT"),
("SIGMA","OUT-WRONG-BUSINESS",
 "Professional TILE CUTTERS and tiling equipment since 1964, Series 4, XL and Tecnica",
 "Tools, an explicit S7.4 exclusion. Reclassify OUT"),
("SQ MOSAIC","BASIC",
 "Pool mosaic collections with textured Squamers finishes and an invitation to customise your own pool. No configurator surfaced",
 "Pool mosaic is the MEC seed niche. Worth an eyeball on what customise your own pool actually means"),
("StoneImpressions/Artisan Stone Tile","ADVANCED",
 "An interactive product customizer: pair stone bases with pattern overlays and mix and match until it fits, plus a visualizer showing patterns on different stone types",
 "Already solved for their own catalogue. The gap is originating a pattern rather than recombining"),
("StyleAccess","NONE",
 "Collections, samples request, get-inspired gallery and displays. StyleLAB is a product line, not a tool",
 "Still the clean test of the 24 Aug S7.4 pivot: designs but does not manufacture, and has no tool"),
("Syzygy Tileworks, Inc.","MANUAL",
 "Colour-ways that customers can use as they are or CHANGE TO SUIT THEIR PREFERENCES, and those colours can be applied to ANY tile and ANY pattern. Glazes brushed on by hand by twenty artisans",
 "Any colour on any shape on any pattern is a combinatorial space no static catalogue can show. Nothing to preview it with"),
("TAGINA","ADVANCED",
 "A design tool for personalising home environments by experimenting with combinations of formats, colours and surfaces, plus a Decors project spanning all products. Confidence medium, confirm by eye",""),
("TIEIC Ceramics","ADVANCED",
 "A 3D Tile Visualizer, plus a Custom Tiles page offering customisation of size, shape, colour and finish across eleven finishes, and a mosaic customisation path",
 "Upgrades my 14 Sept FLAG: they have both the custom offering and the tooling. The open question stays who chooses, them or the importer"),
("Terra Bella","NONE","Stone mosaic collections: pART Deco, herringbone, basketweave, handclipped",""),
("The Rookwood Pottery Co.","MANUAL",
 "Expert designers work with the customer to create a unique tile installation, and USING CAD they create a visual representation of how the installation will look in the customer's home. Endless options from combining shapes, glazes and colour palettes",
 "A person drawing in CAD to show a client their tile before they buy is precisely the job MEC Artworks AI automates. Rookwood has written the manual version into its own sales page. Top-3 hook"),
("Tile by Design, LLC","BASIC",
 "Bring your own image, photograph, logo, design or idea, or choose from 1,000+ stock images. Dye-sublimation murals ship in 2 business days; kiln-fired for outdoors. A numbered installation template ships with every mural",
 "Exact product-category match, fast turnaround, and still no way to preview before ordering"),
("Unique Design Solutions","ADVANCED",
 "Mosaic Creator, billed as Design-Play-Create: design a mosaic FROM SCRATCH, create original designs and patterns or customise existing house blends, with a single-tile preview, a repeat preview AND a VIRTUAL IN-ROOM PREVIEW. Made to order by hand in Phoenix",
 "The most complete US competitor tool found, and it is MEC's feature set minus generative AI. Note two unrelated firms, Onix in Spain and this one in Arizona, both shipped a tool called Mosaic Creator. That is a market telling you what it wants"),
("VILLA CERAMICA","OUT-MIDDLEMAN",
 "Describes itself as a leader in the DISTRIBUTION of ceramic products in Europe. Catalogues and downloads only",
 "Gate 3. Reclassify OUT"),
("WILLIAM F. KEMPF & SON INC","MANUAL",
 "Custom and personalised logo mats, designed and manufactured to requirement, imprinted with vegetable dyes. Everything runs through direct contact, no self-service design",
 "Confirms the criterion-2 question rather than settling it: a genuine custom flat-design loop, in coco and rubber"),
("Winsor Fireform, LLC","MANUAL",
 "300 LPI photographic fidelity, 20,000+ custom colours, in-house graphics and illustration, technical support through concept development, ARTWORK REFINEMENT and production-file prep, with COLOUR PROOFS and control samples before release. Lead time 8 to 12 weeks FROM FINAL ART APPROVAL",
 "The most explicit approval-gated workflow found anywhere: the clock only starts when the art is signed off. But the buyer is an architect or public-art commission, so criterion 1 still fails"),
("X-IS","NONE",
 "Japanese mosaic and tile product pages, chip mosaic and project references such as Conrad Tokyo. No tool",
 "Remember this row is the Cersaie maker X-IS, merged with Wakei & Company, its US stocking arm"),
("XIAMEN ELIN LANDO INDUSTRIAL CO.,LTD","NONE","High-end marble and waterjet mosaics as pre-designed patterns. No tool",""),
("Zaijian Mosaic","NONE",
 "Handmade mosaic art for high-end interiors since 1993, product and case pages only. No consumer-facing design tool",
 "A pioneer of mosaic art in home decoration with no digital design surface at all"),
]

F += [
("TONALITE","BASIC",
 "A Cerca colore colour-finder page and a Stile su misura article. Kraklè runs 4 formats x 16 colours with many special pieces, and decors are described as variably composable into always-original graphic designs",
 "They sell composability in words - 16 colours, 4 formats, freely combinable decors - and give the customer a colour-search page to work it out with"),
("WOW DESIGN","BASIC",
 "Product pages with colour selection, and the Canale collection promoted on almost unlimited placement and combination possibilities with other WOW collections",
 "Same pattern as Tonalite: unlimited combinations promised, no way to try them"),
]

# The export's company names and the names used above differ on a few rows,
# usually because the research used the trading name and the directory used the
# legal one. Mapped explicitly rather than fuzzy-matched, so a wrong join is
# impossible.
ALIAS = {
    'ALFALUX': 'ALFALUX CERAMICHE',
    'APPIANI (Gruppo Bardelli)': 'APPIANI',
    'CEVI CERAMICA VIETRESE (Francesco De Maio)': 'CEVI CERAMICA VIETRESE',
    'COVERLAM (Grespania)': 'COVERLAM',
    'EDIMAX ASTOR': 'EDIMAXASTOR',
    'Hohenberger Manufaktur für Tapeten':
        'Hohenberger Manufaktur für Tapeten I Taubert GmbH & Co. KG',
    'Images In Tile USA': 'Images In Tile USA, Inc. dba Bison Coating & Supply',
}
