# -*- coding: utf-8 -*-
"""Write the hand-researched domains for Heimtextil, TISE and Coverings.

Same method and same columns as tcna_domains.csv: web search over each
company's own indexed pages, never Clay. gate_flag carries the free verdict
that fell out of the research, so rows that cannot pass S7.4 are visible
before any credit is spent.

confidence values:
  high    - the company's own site appeared in results and the city, country
            or business description cross-checks against the directory row
  medium  - a domain is named, but only by a directory or a summary, with no
            independent hit on the site itself. Verify before spending credits
  none    - searched twice, no website exists. Directory or marketplace only
  unresolved - the name is too generic or too thinly indexed to pin down.
            Needs the exhibitor listing itself
"""
import csv

# 'state' held a US state code on some rows and an ISO country code on others,
# which is the exact ambiguity that produced the Bisazza VI bug three times
# (Vicenza province read as Virgin Islands). Two-letter codes collide badly:
# ID is Idaho and Indonesia, IL is Illinois and Israel, IN is Indiana and
# India, CA is California and Canada. So country is now its own column, set
# from the named subdivision map below rather than guessed from the code.
COLS = ['company','domain','alt_domain','city','state','country','confidence',
        'gate_flag','research_note']

# every row whose 'state' value is a US or Canadian subdivision, not a country
SUBDIVISION = {
    'Hanover Architectural Products': 'US', 'SawMaster Diamond Tools, Inc.': 'US',
    'Stanza International LLC.': 'US', 'Stoneyard LLC': 'US',
    'WILLIAM F. KEMPF & SON INC': 'US', 'Yellowstone Rock': 'US',
    'Altura Stone': 'US', 'Andean Stone Company- Simpatico Surfaces': 'US',
    'Bestview International Company': 'US', 'Driftwood Design Labs': 'US',
    'Haussmann Natural Stone': 'US', 'International Wholesale Tile, LLC': 'US',
    'Intrend Tile': 'US', 'Jeffrey Court': 'US', 'Jerusalem Heights': 'US',
    'Keystone Tile': 'US', 'Marazzi/American Olean': 'US', 'PORCEMALL USA': 'US',
    'Roca / Lamosa USA': 'US', 'Stone Partnership Inc': 'US', 'StyleAccess': 'US',
    'Tarmak USA': 'US', 'Terra Bella': 'US', 'TIEIC Ceramics': 'US',
    'Anatolia & Aeterna': 'CA',          # ON is Ontario, Canada
}

HEIMTEXTIL = [
("A.G.M. S.r.l.","","","Casoria","IT","unresolved","EXCLUDE","Heimtextil lists it under Inks and Wallpapers, and its PASTER series is high-concentration pigment preparations for colouring PVC synthetic leather and vinyl coated fabrics. That is a chemical feedstock supplier, not a wallcovering house. D&B places an A.G.M. SRL in Casoria, Napoli, but no company site could be confirmed and searches collide with A.G.M. di Acciaioli (agmtex.it), an unrelated Montemurlo fabric mill. Do not use agmtex.it for this row"),
("A.S. Création Tapeten AG","as-creation.com","","Gummersbach","DE","high","PASS priority","Germany's youngest and one of Europe's largest wallpaper makers, founded 1974. Over 2,000 new designs a year, ~6,000 articles across ~80 collections. Already runs a room visualisation tool where a customer uploads a photo of their own room, so this is the S7.4 has-a-configurator hook, not a rejection, and it belongs in the S11 A/B cohort"),
("AV-Design Inh. Alla Vaysman","","","","DE","none","EXCLUDE","Hall 4.2 pattern studio. Alla Vaysman sells concepts, colorations and designs for wallpaper, fabric, textiles and wrapping paper to manufacturers, which is the output the tool generates. Wrong side of the trade. No website exists either: LinkedIn and Instagram only"),
("Bankside Decor Ltd (Ohpopsi)","ohpopsi.com","","","GB","high","PASS priority","Ohpopsi is the trading brand of Bankside Decor. Bold wallpaper and large-scale wall murals designed by British designers and printed in the UK. Designs in house and sells made-to-order murals, which is criterion 1 and 3 together"),
("Claire Louise Designs","claire-louise.com","","Durham","GB","high","LIKELY OUT revenue","Listed in hall 4.2 but it is not only a pattern studio: Claire Louise designs and then prints onto cushions, kitchenware and gifts sold through John Lewis and Fenwick. So the wrong-side-of-trade reason does not apply. It fails on size instead. An independent illustrated-gift business run by one designer since 2007 will not clear the $1M gate. Verify revenue rather than assuming the hall tells you why"),
("Erfurt & Sohn KG","erfurt.com","","Wuppertal","DE","high","LIKELY OUT","Family firm since 1827 and market leader in PAINTABLE wall coverings, the woodchip and non-woven products a decorator paints over. The product carries texture, not pattern, so a pattern engine has nothing to render. Their 30+ structures are embossings, not designs"),
("Esselle Retail Limited","esselleretail.com","essellehome.com","","GB","high","PASS priority","In-house design team, over 300 live wallpapers, and collections engineered to coordinate wallpaper with fabrics, blinds and rugs. Owns the Arthouse and Esselle Home brands. Coordinating four product categories off one pattern is exactly what a generative engine shortens"),
("Haley Studios Ltd.","haleystudios.com","","Brighouse","GB","medium","EXCLUDE","Hall 4.2 pattern studio. Original hand-painted artwork in gouache and metallic paint, sold for use across surface pattern. Sells designs to manufacturers, so wrong side of the trade. Domain came from a trade directory that printed it as 'ww.haleystudios.com', a typo, so confirm it resolves before use"),
("Hohenberger Manufaktur für Tapeten I Taubert GmbH & Co. KG","hohenberger-wallcoverings.com","hohenberger-atelier.com","Hohenberg an der Eger","DE","high","PASS","Third-generation Bavarian wallpaper manufactory, ~90 years, produces only in Germany, PVC and plasticiser free. Runs both modern digital printing and traditional techniques, and digital printing is what makes short-run bespoke commercially possible"),
("Kaleidoscope Surface Design Olesja Breuer","kaleidoscope-sd.com","","Berlin","DE","high","EXCLUDE","Hall 4.2 pattern studio, founded by Olesja and Vera Bartolomej with Galina Sodolovskaya. Sells exclusively handmade one-of-a-kind patterns to manufacturers. Wrong side of the trade"),
("KBM Sp. z o.o.","kbm.com.pl","wallfix.pl","Belchatow","PL","high","LIKELY OUT","Two businesses, both failing gate 3. It is Poland's leading wallpaper DISTRIBUTOR, reselling Rasch, Hohenberger and Graham & Brown, and it manufactures wallpaper ADHESIVE under the Wallfix and Masterline brands. Adhesive is an explicit S7.4 exclusion and reselling is gate 3"),
("KRITI & KUNAL","","","","IN","none","EXCLUDE","Hall 4.2 pattern studio run by Kriti Sharma and Prince Kunal Gaurav, hand-painted fabrics and murals sold to clients across India, Europe, the US and UAE. Wrong side of the trade. No company website found either, LinkedIn only"),
("KT Exclusive GmbH","kt-exclusive.com","","","DE","high","PASS","Founded 1996 as a manufacturer and editor of high-end wall coverings and fabrics. 'Editor' is the trade term for commissioning and publishing original collections, which is the design step the tool plugs into. Sells worldwide including a KT Architects trade line"),
("Lee Design Studio","","","","","unresolved","EXCLUDE","Hall 4.2 pattern studio and excluded on that basis. The name is too generic to resolve: searches return several unrelated Lee-named surface designers. Needs the Heimtextil exhibitor listing itself if the row is ever revisited"),
("Marburger Tapetenfabrik J.B. Schaefer GmbH & Co. KG","marburg.com","","Kirchhain","DE","high","PASS priority","One of Europe's oldest wallpaper makers, founded 1845, 290 employees, 100% made in Germany, and its collections are created by named international designers. Sells as Marburg Wallcoverings. Named-designer collections plus real scale is the strongest murals-side profile on this list"),
("Norafin Industries (Germany) GmbH","norafin.de","norafin.com","Mildenau","DE","high","EXCLUDE","Technical nonwovens: spunlace, needlepunch and composite roll goods for filtration, performance apparel, medical, automotive, roofing. It sits in the Heimtextil wallcoverings hall as a substrate supplier. There is no pattern and no end customer choosing a design"),
("Onno Raadersma","raadersma.com","","Rotterdam","NL","high","EXCLUDE","Hall 4.2 pattern studio, trading as Onno Raadersma Dessins. Sells dessins for interior fabrics to manufacturers. Wrong side of the trade"),
("Parato S.r.l. (Cristiana Masi)","parato.it","","Aprilia","IT","high","PASS priority","Creating wallpaper collections for international markets since 1985, 100% made in Italy. Cristiana Masi is an architect and the named creative behind every collection, which makes the design step both visible and owned by one decision maker. Small enough that the owner is the buyer"),
("Pufas Werk KG","pufas.de","pufas.com","Hann. Münden","DE","high","EXCLUDE","Founded 1928, makes products for painters and decorators: pastes, adhesives, fillers, cleaners. A trade-supply company in the wallcoverings hall, not a wallcovering designer. Explicit S7.4 exclusion"),
("Rafias Prisim Textil S.r.l.","rafiasprisim.com","","Valentin Alsina, Buenos Aires","AR","high","LIKELY OUT","Note the country: the S.r.l. suffix reads Italian but the company is Argentine, in Valentin Alsina, Buenos Aires, since 1966. Hall 4.1, and the product is natural-fibre fabric in cotton, raffia, jute and linen. Woven texture, not printed pattern, so there is no design step to render"),
("SANDRA JACOBS DESIGN","","","Vught","NL","none","EXCLUDE","Hall 4.2 pattern studio. Dutch artist selling handpainted and digital designs for home and fashion textiles, historically to Lacroix, YSL and Armani. Wrong side of the trade. No own website: LinkedIn, Instagram and Maison&Objet listings only"),
("Textiles Vilber S.L.","vilber.net","vilber.es","Tavernes de la Valldigna","ES","high","PASS","75+ years, supplies 60 countries, and manufactures fabrics, WALLPAPERS and vinyl flooring for home and contract decoration. The wallpaper line puts it in scope. Confirm on the site whether wallpaper is a real design line or a small side range before prioritising"),
("The Wallfashion House NV","grandecogroup.com","","Tielt","BE","high","PASS priority","This is Grandeco Wallfashion Group, founded 1978, Europe's largest wallpaper producer: 20 million rolls a year in more than 1,000 designs, ~EUR 150M turnover, 600+ people across ten European sites, sold in 88 countries. A thousand new designs a year is the largest design throughput on the whole wave-2 list. PE-backed by GIMV and Down2Earth, so a long cycle, but the pain is real"),
]

TISE = [
("COMES NORTH AMERICA, INC","","","","US","unresolved","EXCLUDE","Searched twice. Most likely the North American arm of an Italian stone-machinery maker, either Comes Italy (comesitaly.it, Tito, Potenza) or CO.ME.S Costruzioni Meccaniche Signorini (come.it, Calcinaia), both of which build marble and granite processing machinery. Machinery is an explicit S7.4 exclusion, so the row is out whichever it is and the domain does not matter"),
("DOOHA CO., Ltd","dooha.net","","Jincheon","KR","high","LIKELY OUT","40 years old, sells itself on precision machining and quality control from its Jincheon plant. An industrial component maker exhibiting in a surfaces hall. No pattern, no design step"),
("Echelon Surfaces","","","","US","unresolved","LIKELY OUT","Searched twice, no match. Do NOT use echelontileandstone.com: that is Echelon Tile and Stone, a different Tri-State fabricator and installer, and fabricator-installer fails gate 3 anyway. Echelon Masonry is an Oldcastle brand, also a different company. Needs the TISE exhibitor listing"),
("Franken Schotter GmbH & Co. KG","franken-schotter.com","","Dietfurt","DE","high","LIKELY OUT","Germany's leading Jura limestone and dolomite producer: four quarries, ~350,000 tons of raw block a year, ~2 million tonnes of product, 500+ employees. A quarry operator selling wall cladding and floor slabs. Raw stone, no pattern"),
("Hanover Architectural Products","hanoverpavers.com","hanoverpaversathome.com","Hanover","PA","high","LIKELY OUT","American-made concrete unit pavers since 1971. Hardscape construction material specified by landscape architects. No customer-facing design step for the tool to sit on"),
("i4F Patents & Technologies","i4f.com","","","NL","high","EXCLUDE","Not a product company at all. i4F licenses a portfolio of 2,000+ patents, mainly floor locking systems, to 100+ flooring manufacturers. There is no product, no pattern and no end customer. Nothing to plug a design tool into"),
("JADRANKAMEN white limestone Croatia/EU","jadrankamen.hr","","Pucisca, Brac","HR","high","LIKELY OUT","Quarries white and semi-white marble from eleven quarries on the island of Brac and processes it at two plants. Extraction, processing, sale and installation of building stone. Quarry plus installer, two gate-3 problems"),
("MIGA (Shinil Frame Co.,Ltd.)","migaworld.com","shinilframe.co.kr","Paju","KR","high","EXCLUDE","Founded 1967, makes polystyrene moulding, frame and panel under the MIGA brand, ~100 patents, exports to 60 countries. Moulding and frame, not a flat patterned surface. Wrong medium"),
("PRINTECH KR CO., LTD.","printechkr.com","","Paju","KR","high","LIKELY OUT","Spun out of LG Chem's decopaper division in 1999 and Korea's decopaper market leader since 2004. It does print decorative pattern, on paper, under the Lovenre brand, so it is closer than most TISE rows. But it sells that paper as a raw surface material to furniture and panel makers, who choose the design. The design decision sits with their customer, not with them"),
("SawMaster Diamond Tools, Inc.","sawmaster.com","","Riverside","CA","high","EXCLUDE","Founded 1997, family owned, makes saws, diamond blades and accessories for cutting tile, marble, masonry and concrete. Tools are an explicit S7.4 exclusion"),
("Stanza International LLC.","stanzawholesale.com","","Chino Hills","CA","high","LIKELY OUT","Pebble tile since 2005, about 50 styles of flat, standing, polished and flower pebble mosaic. By its own description it receives its tiles directly from one of the largest manufacturers in China, so it is the importer, not the maker. Gate 3"),
("Stone Factory","","","","","unresolved","LIKELY OUT","Unresolvable by name: at least three unrelated US companies trade as The Stone Factory (thestonefactoryco.com, thestonefactory.net in Orange CT, thestonefactorypalmbeach.com), all of them stone importers or fabricators. Needs the TISE listing, and the row fails gate 3 on every candidate"),
("Stoneyard LLC","stoneyard.com","","Littleton","MA","high","LIKELY OUT","Manufacturer of New England natural thin stone veneer, cut from real fieldstone. A genuine maker, but the medium is stone veneer for siding and walls, with no pattern to design. Worth noting they already run a Stone Visualizer, so the tooling instinct is there, wrong product"),
("WILLIAM F. KEMPF & SON INC","williamkempf.com","","Folcroft","PA","high","FLAG criterion 2","Not stone despite the TISE hall: since 1886 this firm makes coco mats, recycled tire tiles and CUSTOM ENTRANCE MATS. A custom logo mat is genuinely a flat 2D custom product with a client approval step, so criterion 1 and 3 arguably hold and this is not an automatic drop. The question is criterion 2: whether the engine renders a coco or rubber mat usefully. Shahwaz's call, same class of question as the parked niches"),
("Yellowstone Rock","yellowstonerock.com","","Idaho Falls","ID","high","LIKELY OUT","The largest quarrier and fabricator of domestic travertine in the US, quarries in the Greater Yellowstone area, fabrication in Idaho Falls. Quarry plus fabricator. Raw stone, no pattern"),
]

COVERINGS = [
("AIXIN TECH.CO., LTD","ralartmosaictile.com","","Foshan","CN","high","FLAG","Trades as Ralart Mosaic, founded 2011, renamed Aixin Technology in Oct 2024. Range includes mosaic ARTS and mosaic MURALS alongside commodity glass and ceramic mosaic, so unlike most Foshan rows there is a custom-design side. Tier 3 geography and a supplier model pull the other way. Check whether mosaic art is a real commissioned line or a catalogue"),
("Akgun Seramik/Dura-tiles","duratiles.com","duratiles.com.tr","Istanbul","TR","high","LIKELY OUT","Duratiles is the brand of Akgun Seramik: 380 million sq ft a year from five plants in Turkey and Bulgaria. Fixed-SKU volume porcelain with accessories, step treads and borders. Nothing a customer designs, so criterion 3 fails"),
("Altura Stone","alturastoneandtile.com","","Miami","FL","high","LIKELY OUT","Its own strapline is Importer and Distributer of Natural Stone. Family owned since 2007, stocks marble, limestone, travertine, onyx and granite in 100,000+ sq ft of warehouse across Miami, Atlanta and Fairfield NJ and sells through dealers. Gate 3"),
("Anatolia & Aeterna","anatolia.com","","Woodbridge","ON","high","LIKELY OUT","A leading IMPORTER and DISTRIBUTOR of ceramic and stone, supplying the largest distributors across the US and Canada from a 600,000 sq ft facility. Aeterna is its own premium sintered-slab brand, so there is brand-level design, but the business is distribution. Gate 3"),
("Andean Stone Company- Simpatico Surfaces","andeanstonecompany.com","","Hialeah","FL","high","LIKELY OUT","The Miami sales, warehousing and logistics centre for Minera Roca Andina, a Peruvian quarry group, supplying travertine, limestone and marble from the high Andes. A distribution arm for a quarry. Gate 3 plus raw stone"),
("Arts Co., Ltd","","","Dongguan","CN","none","LIKELY OUT","Resolves to Dongguan Arts Co., Ltd, established 2002 near the Foshan ceramics base, making recycled glass mosaic, ceramics, cement products and terrazzo. No company website found, trade platforms and the Coverings listing only"),
("Arvex Srl.","arvexmosaic.com","","Mondolfo","IT","high","FLAG","Founded 1988, develops AND distributes mosaics and tiles in terrazzo, marble, glass and porcelain. Mosaic is a core S7.4 niche and 'develops' points at real in-house design, but 'distributes' and a worldwide dealer network point at gate 3. Needs the site read properly before a verdict"),
("Asia Dynasty Resources Pte Ltd","asiadynasty.com","","Singapore","SG","high","LIKELY OUT","Registered 2014, describes itself as a supplier of premium tile, stone and mosaic that collaborates with mills in China and Malaysia. Singapore business records also class it as a tile contractor. Reseller plus contractor, gate 3 twice"),
("Asia Pacific Ceramic","asiapacificceramic.com","","Morbi","IN","high","LIKELY OUT","Established 2001 in Morbi, 10 million sq m a year on Italian lines, ~70% exported. Volume porcelain slabs and tiles to a catalogue. Criterion 3 fails"),
("AVANGARDE CERAMICHE","avangardeceramiche.com","","Foshan","CN","medium","LIKELY OUT","An Italian-sounding brand operating out of Guangdong, supplying glazed and unglazed ceramic, floor, mosaic and porcelain tile. Domain came from a trade directory rather than a confirmed live site, so verify. Commodity supplier either way"),
("Bar-On Studio","baron-studio.com","","Petah Tikva","IL","high","PASS priority","The best Coverings row on the list. Founded in Israel in 2010 by three brothers, family owned, and it BOTH designs and manufactures: sculptural concrete decorative wall coverings, curated concrete tiles, and tiles with integrated lighting, from its own Petah Tikva factory and showroom. Sells into the US since 2014 and through Ann Sacks since 2017, so it is trade-facing and already US-proven. Designs in house, makes in house, flat decorative wall surface, owner-operated"),
("Bestview International Company","bestviewintl.com","","Glenview","IL","high","LIKELY OUT","Self-describes as manufacturer AND importer of natural stone: granite, marble, onyx, travertine, slate in 100+ colours, plus countertops, vanities and mosaics. Six-time MIA Pinnacle winner. Stone fabrication and import, not pattern design"),
("BiQslab","biqslab.com.tr","","","TR","high","LIKELY OUT","Bien's large-format slab brand, running 350-metre kilns. Volume slab production. No customer design step"),
("Bluetone Ceramic","bluetoneceramic.com","","Morbi","IN","high","LIKELY OUT","Established 2013, manufactures and exports porcelain floor tile from Morbi. Related entity Bluetone Impex is listed as a trader and wholesaler. Commodity catalogue"),
("Cerámica Italia S.A","ceramicaitalia.com","","Cucuta","CO","high","LIKELY OUT","Colombian maker with 30+ years and 1.3 million sq m a month of capacity aimed at large American orders. Volume catalogue for floors, walls and bathrooms"),
("Cinca","cinca.pt","","Fiaes, Santa Maria da Feira","PT","high","LIKELY OUT","Founded 1964, started in 2.5x2.5cm porcelain mosaic, now ~5.2 million sq m a year into 70+ countries, part of Gruppo Cerdisa Ricchetti. Mosaic is in the ICP but the business is volume catalogue production"),
("Cosa Marble Co.","cosamarble.com","","","US","high","LIKELY OUT","A US wholesale distributor of marble, limestone and onyx. Worth one note: the range includes borders, MEDALLIONS and mosaics, and a medallion is a custom flat 2D design. But the company distributes rather than designs. Gate 3"),
("Driftwood Design Labs","driftwooddesignlab.com","","","CA","high","PASS priority","A creative studio and a division of Lunada Bay Tile, Southern California. Own collections: Zel Moroccan zellige, Cotto Andaluz terracotta, Shoreline, with hand-painted and handcrafted elements. Designs original collections and makes them, which is the profile the ICP was written around. Note the competitor conflict: Lunada Bay is a tile and mosaic house, so this row takes the S7.9 walkthrough CTA with no link to MEC's tool"),
("E-CERAMIC","","","","","unresolved","LIKELY OUT","Too generic to resolve. Searches collide with Eco Ceramica (ecoceramica.com), an unrelated 27-year Italian wall and floor tile maker. Do not use that domain for this row. Needs the Coverings exhibitor listing"),
("Favorita Marmi e Graniti SpA","granitifavorita.com","","Lonigo","IT","high","LIKELY OUT","Conterno family, 60 years, selects and processes marble, quartzite, granite, onyx and semi-precious stone slabs in the Vicenza marble district. Slab processing, no pattern design"),
("Foshan Domogres Building Materials LTD.","dozanmosaic.com","","Foshan","CN","medium","LIKELY OUT","Founded by Franki Lee, supplies glass, marble, pool, recycled glass and porcelain mosaic plus waterjet and decor tile. Exports mainly to the US, Canada and Ecuador. The operating site appears to be dozanmosaic.com rather than anything matching the registered name, so verify. Commodity mosaic supplier"),
("Foshan Hengsheng New Material Co., Ltd.","hengxingmosaic.com","","Foshan","CN","high","LIKELY OUT","Glass mosaic specialist since 2008, 2,000+ models with new items monthly, into hotels, pools and bathrooms. High SKU churn, no customer design step"),
("Graiman CIA Ltda.","graiman.com","","Cuenca","EC","high","LIKELY OUT","Founded 1992 with Ecuadorian capital, first technical porcelain producer in Ecuador and on the Pacific coast, now digital printing and large format. Producer and national distributor. Volume catalogue"),
("Haussmann Natural Stone","haussmannstone.com","","Hayward","CA","high","LIKELY OUT","A distributor with 40+ limestone options in stock, offering custom solutions across North America. Limestone distribution. Gate 3 plus raw stone"),
("HOMEE FOSHAN CO .LTD","homeemosaic.com","","Foshan","CN","high","LIKELY OUT","Founded 2005, dedicated solely to R&D and production of mosaic tile, export focused into North and South America, Europe and Australia. Real mosaic manufacturer but a high-end catalogue supplier, not a design-to-approval business"),
("Honor View Enterprise Co., Ltd.","","","","TW","unresolved","LIKELY OUT","A Taiwanese tile supplier visible only in import records, shipping to The Tile Shop in Plymouth MN. Do NOT use honortile.com: that is Zibo Honor Ceramic, an unrelated Chinese maker. Needs the Coverings listing"),
("Ibel","ibelceramics.com","","Foshan","CN","medium","LIKELY OUT","Brand created in 2006 to supply ceramic tile and deco accessories to architects, builders and importers of building materials worldwide. Domain came from a summary rather than a confirmed live page. Supplier to importers, gate 3"),
("IKAD X MUZZI TILE INDONESIA","ikad-intl.com","","Jakarta","ID","high","LIKELY OUT","IKAD and MUZZI are two brands of an Indonesian porcelain manufacturer, designs developed by Italian and Chinese teams, in standard sizes from 12x24 to 32x32. Volume catalogue"),
("IMEX INTERNATIONAL CO., LTD","imexinter.com","","Bangkok","TH","high","LIKELY OUT","Founded 1994, produces glass, ceramic and porcelain tile on high-technology lines. Coverings lists it under decorative, glass, mosaic and porcelain tile. Volume producer"),
("Inno Stone","","","","","unresolved","LIKELY OUT","No match after searching. Results collide with Inno Stickers (peel-and-stick), Innovation Stone & Tile and Stone Innovations, all unrelated. Needs the Coverings exhibitor listing"),
("International Wholesale Tile, LLC","internationalwholesaletile.com","","Palm City","FL","high","LIKELY OUT","Trades as Tesoro. Supplies porcelain, ceramic and natural stone to retail floorcovering stores, design centres and specialty tile shops nationwide. The name states the business model. Gate 3"),
("Intrend Tile","","","Brea","CA","none","FLAG no domain","Genuinely interesting and genuinely unreachable. A mosaic tile company in Southern California started by two friends from art school who wanted to make their own designer tiles, with an office and showroom at 272 Gemini Ave, Brea CA. That is an ICP profile. But it has no website: it sells through Amazon, Wayfair, Perigold, AllModern and Faire. Do NOT use intrend.co.in, an unrelated Indian wall-tile company. Needs a manual look or a phone call"),
("ITACA CERAMIC PRIVATE LIMITED","itaca.in","","Morbi","IN","high","LIKELY OUT","Founded 2009 by Kiran Patel, promotes Italian-styled design into Indian homes, 200+ employees, large-format wall and floor tile and slabs. Volume catalogue"),
("Italica Tiles","italicatiles.com","","Morbi","IN","high","LIKELY OUT","Formed 2004, one of India's leading suppliers and distributors of large-format wall and floor tile, exporting to 85+ countries. Supplier and distributor at volume"),
("ITALMOSAICO","","","","IT","unresolved","LIKELY OUT","Could not be resolved. Searches return unrelated Italian mosaic businesses: Fantini Mosaici, Orsoni Smalti, the Ravenna Mosaic Art School, Italian Mosaic Masters. Worth a second look from the Coverings listing, because an Italian mosaic house would be on-niche if it designs"),
("Jeffrey Court","jeffreycourt.com","","Norco","CA","high","PASS priority","Started in 1991 by Jim and Janice Lawson as a HAND-PAINTED tile business and still describes itself as producing high-end decorative mosaic tile, 30+ years on, distributing nationally from Norco CA. Founder-led, decorative, mosaic. Competitor conflict with MEC, so walkthrough CTA, no tool link"),
("Jerusalem Heights","jerusalemheights.com","","Milford","CT","high","PASS","A producer and manufacturer of natural stone mosaic tile, premium marble mosaics for backsplashes, shower floors and walls. Makes its own mosaics in Connecticut. On-niche and on-medium. Competitor conflict with MEC, so walkthrough CTA"),
("Keen Ocean Asia Ltd/NOVA Breeze SDN.BHD.","","","","MY","unresolved","LIKELY OUT","Established 2002, manufactures glass, stone and metal mosaic and has exported to North America for 21+ years. No company website surfaced, only the Coverings listing. Commodity mosaic manufacturer"),
("Keramicos","keramikos.com.ec","","Cuenca","EC","medium","LIKELY OUT","Two things share this name in Cuenca and they matter differently. keramikos.com.ec is Keramikos S.A., the retail and distribution arm and Porcelanosa's Ecuador distributor, with boutiques in Cuenca, Guayaquil and Quito. The Coverings exhibitor is the producer group behind Ceramicas Rialto, Ecuaceramica and Italpisos. Either way it is distribution or volume production. Verify which entity the listing means"),
("Keystone Tile","keystonetile.com","","Houston","TX","high","LIKELY OUT","Runs a 300,000 sq ft Houston showroom and warehouse plus 673,000 sq ft in Florida and 130,000 in Atlanta, selling porcelain, pavers, travertine, marble and pool coping. Warehouse and showroom distribution. Gate 3"),
("LAXVEER CERAMIC LLP","","","Morbi","IN","none","LIKELY OUT","Incorporated Dec 2016 in Morbi, makes glazed porcelain tile and granite slab, also trades as LV Granito. Its own company registration records list the website as Not Available, so this is a confirmed no-site row, not a failed search. Commodity producer"),
("Lourdes SPL Argentina","ceramica-lourdes.com.ar","","","AR","medium","LIKELY OUT","Industrias Ceramicas Lourdes, wholly Argentine, 25 years, the first Argentine and second Latin American company to run a digital production line. SPL is its San Pietro Laminas product. Digital printing at volume, still a catalogue"),
("Marazzi/American Olean","marazziusa.com","americanolean.com","Dallas","TX","high","FLAG enterprise","Two brands, both Dal-Tile and therefore Mohawk: Marazzi since 1935, American Olean since 1923. Genuine design operations but a 200+ enterprise, which per the S7.4 decision-maker table means a Head of Design or digital lead and a long cycle. Tag separately and deprioritise rather than drop"),
("Marmotech, S.A.","","","","","unresolved","LIKELY OUT","Four unrelated companies use this name, in the Dominican Republic (marmotech.com.do), Turkey (marmotech.com.tr), Saudi Arabia (marmotech.co) and Egypt with US operations (marmotech-us.com). Cannot be pinned without the Coverings listing. All of them extract, cut, polish or distribute marble, so the row fails gate 3 whichever it is"),
("Maruman Shokai. Co., Ltd.","tile-maruman.com","","Tajimi","JP","high","PASS priority","Founded 1931 by Manzo Kato, incorporated 1957, in Tajimi, the centre of Japanese tile production. 65+ years making porcelain MOSAIC tile, 100% made in Japan, local mineral clays, natural glazes, 24-hour firing, with Majolica and Deco named lines. A real artisan mosaic maker with named collections. Competitor conflict with MEC, so walkthrough CTA"),
("Maxfato","maxfato.com","","Foshan","CN","high","FLAG","Stands out from the other Foshan rows: it describes itself as DESIGNING and producing mosaics and tiles for clients, with commercial offices in Spain, Mexico, Australia and Brazil alongside the Foshan HQ and showroom. Range spans metal, porcelain, natural stone, engineered stone and craft glass. 'For clients' suggests project and custom work. Worth a site read"),
("MG Surfaces Limited","","","","","unresolved","LIKELY OUT","No company of this exact name found. Nearby names are all different companies: MMG Tile & Stone (mmgmarble.com), MG Stone Surface (mgstone-surface.com), Marble & Granite Designs UK (mgduk.com). Do not assume any of them. Needs the Coverings listing"),
("Natamar","natamar.com","","Denizli","TR","high","LIKELY OUT","25 years producing travertine from Denizli, selling to chains and wholesalers in 30+ countries. Travertine production plus wholesale. Raw stone, gate 3"),
("NG Kutahya Seramik","ngkutahyaseramik.com.tr","","Kutahya","TR","medium","LIKELY OUT","Part of NG Group, interior and exterior ceramic across many models and sizes, sold to architects, builders and designers. Domain from a summary rather than a confirmed page, so verify. Volume catalogue"),
("PADUA CERAMICS PTE. LTD.","","","Singapore / Foshan","SG","unresolved","LIKELY OUT","Registered in Singapore in Sept 2019, principal activity recorded as wholesale of structural clay and concrete products, operating out of Foshan. Designs and produces porcelain stoneware for commercial, public and residential space but has no findable website, only an Instagram. Wholesale, gate 3"),
("Pavigres Ceramicas, S.A.","pavigres.com","","Aguim, Anadia","PT","high","LIKELY OUT","Founded 1978 by Oswaldo Martins, merged with Grespor and Cerev in 2004. Portuguese volume wall and floor tile. Catalogue production"),
("Pavit Ceramics","pavits.com","","Ahmedabad","IN","high","LIKELY OUT","Established 1989, India's largest full-body porcelain maker, brands PAVITS and VICTORY, present in 40 countries. Already runs a tile visualizer, so it belongs in the has-a-configurator note, but the product is a fixed catalogue so criterion 3 still fails"),
("PORCEMALL USA","porcemall.com","","Deerfield Beach","FL","high","LIKELY OUT","Founded 2002, US arm since 2014, a distributor of floor and wall tile imported from Europe and Asia, sold through 500+ authorised stores in Florida. Gate 3"),
("PT. Sun Power Ceramics","sunpower.id","","Mojokerto, East Java","ID","high","LIKELY OUT","Since 2010, a benchmark in marble-effect ceramic surfaces on Italian technology, five finishes, standard colour families. Volume catalogue"),
("Qingdao Century Import & Export Co., Ltd","qdcentury.com","","Qingdao","CN","high","LIKELY OUT","Established 2005, exports slabs, tile, mosaic, countertops, vanity tops, sinks and landscape stone, working with dozens of partner factories in Xiamen plus two of its own in Shandong. The name is the business model. Gate 3"),
("QUA","qua.com.tr","","Aydin","TR","high","LIKELY OUT","QUA Granite started production in 2016 and now runs Turkey's largest technical-granite-only plant at 41 million sq m a year with 1,000+ employees, exporting to 100+ countries. Pure volume. Criterion 3 fails"),
("Roca / Lamosa USA","rocatileusa.com","","Miami","FL","high","FLAG enterprise","Roca Tile's tile division was bought by Grupo Lamosa in Sept 2021 and the two run together as ROCA TILE USA and LAMOSA USA, with design studios and showrooms in Miami, Chicago and New York. 100+ years of manufacturing and distribution. Same call as Marazzi: real design operation, enterprise buyer, long cycle, deprioritise rather than drop"),
("SAXOLIA by italcrafts","saxolia.it","italcrafts.it","Fiorano Modenese","IT","high","LIKELY OUT","Saxolia is the house brand Italcrafts launched into North America in 2021. Italcrafts itself, since 1976, is a TRADING company in tiles and furnishing accessories and the market leader in Africa and the Caribbean. A trader with a private label. Gate 3"),
("Seed Decorative Material Co., Ltd.","","","Foshan","CN","none","LIKELY OUT","Established Nov 2002 in Shunde, Foshan, manufactures crystal mosaic at 450,000 sq m a year. No own website: Alibaba, Made-in-China and the Coverings listing only. Commodity manufacturer"),
("Shanghai Tongchen Stone Co., Ltd.","tongchenstone.com","","Shanghai","CN","medium","LIKELY OUT","One of China's leading white marble suppliers and exporters, four production bases in Shanghai, Sichuan, Fujian and Jiangsu Yixing. Domain from a summary, verify. Raw stone export"),
("Stone Partnership Inc","stonepartnership.com","","Pennsauken","NJ","high","LIKELY OUT","40+ years as a wholesale distributor of natural stone, specialising in honed, antiqued and distressed material. Wholesale distribution. Gate 3"),
("Stoneglass Srl.","stoneglass.it","","Casciana Terme Lari, Pisa","IT","high","LIKELY OUT","Stoneglass is a crystallised glass-stone MATERIAL made in Tuscany, specified by architects for cladding, ventilated facades, flooring and marine use. A material brand, not a pattern designer"),
("Stover's LLC","stoversliquidation.com","","","US","high","LIKELY OUT","Describes itself as the largest stocking dealer of ceramic and porcelain tile, laminate and hardwood in the South, trading as Stover's Liquidation. A stocking dealer clearing inventory. Gate 3, and the liquidation model means no design step at all"),
("StyleAccess","style-access.com","","Carrollton","TX","high","FLAG","The most arguable row on the list. An importer, DESIGNER and distributor that owns Lungarno Ceramics (2013, designer-led collections including handmade wall tile) and CommodiTile (2017), and says it is involved in all phases of the tile design process while sourcing production from Asia and Europe. So it designs but does not manufacture. Under the 24 Aug S7.4 pivot 'makes the product themselves' is no longer a hard gate, which means this row now qualifies on criteria 1 and 3 where it would have been dropped before the pivot. A clean test of whether the pivot was right"),
("TAB Surfaces - Natural Stone and QUARTZ","tabindia.com","tabquartz.com","Hosur","IN","high","LIKELY OUT","One of the largest natural stone and quartz processors in the world: granite, marble, slate, quartzite, sandstone, limestone plus the TABQUARTZ engineered line. Slab processing. No pattern"),
("Tarmak USA","tarmakusa.com","","Tampa","FL","high","LIKELY OUT","Founded 2002 and states plainly that it is a DIRECT IMPORTER of natural stone tile, mosaic, tumbled stone, moulding, slabs and trim, bringing containers from Turkey, Italy and China into Tampa inventory. Gate 3"),
("Tendenzza","","","","MX","unresolved","LIKELY OUT","Tendenzza Pisos y Recubrimientos SA de CV, a Mexican porcelain tile brand sold through Azulemex, Surtidor and Construrama, with collections like Carrara, Nero, Imperia and Novara. No own corporate site found. Volume catalogue"),
("Termal Seramik","termalseramik.com.tr","termalseramik.com","Sogut, Bilecik","TR","high","LIKELY OUT","Founded 1995, reached 24 million sq m a year after 2018 investment, producing standard-size porcelain floor, wall and parquet tile. Pure volume"),
("Terra Bella","terrabella.design","","Clifton","NJ","high","FLAG","Self-describes as manufacturer, importer AND US distributor of ceramic, stone and glass mosaic. All three roles in one sentence, so the maker share is unknown. Mosaic is on-niche and the company is small enough for the owner to be the buyer. Worth a site read rather than a drop"),
("TIEIC Ceramics","tieic.com","","","PA","high","FLAG","A Pennsylvania-registered entity selling tile made in Morbi into North America, and the one commodity-adjacent row with a real design hook: it runs dedicated CUSTOM TILES and MOSAIC pages offering customisation of size, shape, colour and finish. That is criterion 1 and 3 on paper. The catch is that its stated customer is the North American IMPORTER, not an end customer, so confirm who actually makes the design choice"),
("Tile Park Japan","tile-park.com","sg.tile-park.com","Kani, Gifu","JP","medium","FLAG","A platform rather than a maker: it aggregates premium Japanese tile and supports designers with free samples and BIM data. TN Corporation manufactures porcelain in the same Gifu region and may be the operator. A specifier-facing marketplace could be a channel partner rather than a prospect. Only regional sites surfaced, so verify the primary domain"),
("Travertini Paradiso Srl.","travertiniparadiso.com","gruppodei.it","Serre di Rapolano","IT","medium","LIKELY OUT","Founded 1907-08, part of Gruppo Dei which the Dei family has owned since 1960, extracting and processing travertine in Rapolano Terme. Two domains appear for it, so confirm which is current. Quarrying and processing, no pattern"),
("Trend Surplus Development, Ltd.","","","","CN","unresolved","LIKELY OUT","Specialises in marble, glass, ceramic and metal mosaic and sells under the brand Chroma Mosaico. No own website surfaced, only a trade directory. Note the name collides with TREND Group (trend-group.com), a well-known and unrelated Italian mosaic house. Commodity mosaic supplier"),
("Turkishceramics","turkishceramics.com","","Balgat, Ankara","TR","high","EXCLUDE not a company","Not a prospect: Turkishceramics is the state-backed export promotion group for Turkish ceramic manufacturers, set up in 1997, representing 30+ member companies. There is nobody here to buy a tool. It is a SOURCING lead though, since its member directory is a free, pre-filtered list of Turkish tile makers"),
("WINASA CERAMICA","winasaceramica.com","","Morbi","IN","high","LIKELY OUT","20+ years in Morbi, manufactures and exports ceramic wall and floor tile, polished glazed vitrified, parking tile, slabs and sanitaryware. Sanitaryware is an explicit exclusion and the rest is commodity catalogue"),
("X Ceramics Group","xceramics.com","","","BD","high","LIKELY OUT","A leading player in Bangladesh's ceramic market selling premium Italian tile under the X Monica, X Monalisa and X Alexander brands, plus bathware. A brand portfolio over imported product. Gate 3"),
("XIAMEN ELIN LANDO INDUSTRIAL CO.,LTD","elinlandomarble.com","","Xiamen","CN","high","FLAG","Built by Portia Guo in 2013-14 and describes itself as a SPECIALTY MANUFACTURER of high-end natural stone mosaic, field tile and countertops, booked at Verona and Coverings. A small, founder-run mosaic maker rather than a trading house, which separates it from the other Xiamen rows. Tier 3 geography and stone rather than printed pattern are the arguments against"),
("XIAMEN STONELINK IMP. & EXP. CO. , LTD","","","Xiamen","CN","none","LIKELY OUT","12+ years as a stone project supplier offering a one-stop stone solution, 252 shipments to 33 buyers mainly in Indonesia, the US and Vietnam. No independent website: Alibaba and Facebook only. Import and export, gate 3"),
("YUKARI CERAMICS","yukariceramics.com","","","JP","high","PASS priority","Born from uniting Italian design culture with Japanese ceramic craftsmanship, and every tile is designed by hand by Japanese artisans. Note the geography: despite sitting in a Coverings row next to Turkish brands, this is Japanese and Italian, not Turkish. Hand-designed artisan tile with named collections. Competitor conflict with MEC on the tile side"),
("Zaijian Mosaic","zaijianmosaic.com","","Chengdu","CN","high","PASS","Founded 1993 and one of the pioneers that brought MOSAIC ART into home decoration, now a significant force in global mosaic, doing stone mosaic, art mosaic and lava. Art mosaic means commissioned custom work, which is the approval-wait the tool removes. Tier 3 geography and a direct MEC competitor, so walkthrough CTA"),
]

RAW = ['company','domain','alt_domain','city','state','confidence','gate_flag','research_note']

def write(path, rows):
    out = []
    for r in rows:
        d = dict(zip(RAW, r))
        code = d['state']
        sub = SUBDIVISION.get(d['company'])
        if sub:                       # code is a state or province
            d['country'] = sub
        elif code == 'US':            # already a country, no subdivision known
            d['country'], d['state'] = 'US', ''
        else:                         # code is an ISO country code, or blank
            d['country'], d['state'] = code, ''
        out.append(d)
    with open(path,'w',newline='',encoding='utf-8-sig') as f:
        w = csv.DictWriter(f, fieldnames=COLS, quoting=csv.QUOTE_ALL)
        w.writeheader(); w.writerows(out)
    bad = [d['company'] for d in out if not d['country']]
    print(f'{path}: {len(out)} rows' + (f'  ({len(bad)} with no country: {bad})' if bad else ''))

write('heimtextil_domains.csv', HEIMTEXTIL)
write('tise_domains.csv', TISE)
write('coverings_domains.csv', COVERINGS)
